language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.3.3
env:
  global:
    secure: Q5/UDGpP3h51ObE8YQYSR70SecHNk0B9oYIL5xxL7Pe9ppcAFXY7J/PAUC+pAH3wAxSQt9guMxP01moXEpBkUU1Gn6oM9JOLh4b3j/Ub/B10WCngXFQLMsYKuExWMv2f4ClNn9UazRDGTtqtFUP41a7mFnb1E8vtfwr0GGcGSe7f05ZEaPZ9fsjhv6rO23cK5EXI7sIj+jidLpV6C9KQMnRZo7HzfF3iXzEtK6sl/QnM+SMSQmaqSeMndOOQx7vl7Q6OHdJIrma3luDOjifuzyxul3t/BWBoLuFDgW9OXIzFISg/AE61MWYQKrX/aWv7RPb5OwsCf+XGBCTeTDoSW5E9sdTihOev+JXbl963nLF3NlNWBykwYmEq7NK8h2AT+Ugv1baAyiouvaR/5kQ9vfK4T6HEr0zEqcIDEoA9cKW8uByHo2VlO12QnCrcOmg3QsK8ekHYZlCxx9hp2JYLx3Xz3722pHAZa1IL+8DTp15gkCxkMQchDlCA71sz1WSuwF2jH/d8aGH/UwbZd/XEBHAfKq65eMv6ValRhrrK6xpeXjKGm8Ahh8rMo96JbaPw50lFjRFWLQVEArEcOJGvP6zb8KlrSb/cjMJjhsWEGVjAgffh3G0JS3MUDnAuG//MJnKfpJH5yOR43/XaJOxwPl2UE7vXIh15W47Ti6Pmew4=
