language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.3.3
env:
  global:
    secure: kPV71Dzu9pJehoitasoTE323WheF6DbuXJMm64Zvd+WLEhz26nufmYSI3IpCQFEM++E5nAJNbS88cQtIPFNHv8q6ciw4GKVToXxhr/7jUJbbW7esrOY69fr6BPgB2a/eAXyC1GIu3VVjmjXSOfPOoO/6x0QNAe4n/n8S3yif8ug8GBzDZflaoxEs0N1wlmwVvNdGAa6tDl1dBsnZmdQmu/P0bOtVlvi2CZ+5d7S/Kps+qP2pB1fm0x/GvJzF48Uq40bSlrG0f5OxRdNpSFXQMlmSP5yy0GcOkkDisBlbvdsiP6vO3IDCM5RJ6TmXosiFDVEE6E6oEgSJCgWm9FVfXck0Z/HGinSNK1SlARRTVPpGlG+HIrWRIq7ZCNmivqAmau3EimyG1KI5skjDrBx5rrS8FZmWJxe2BBhfGUp3KA7iFZHgfIvi86vzmB4l4UxNsEkrMwLJMLHpzv9KnG8IDab/fEpmaIrFOQYLfY+8mm8JwioFB2W9i6/A7+aYJcCWG2t9+ZqFhrsTWk0bo2ZiBNPVtZOxgg4CqzbSli3pzpiXN7gan81VzBVxByiHGG2LjoAyJ8+Jc0e+hvLMhBeiAHk3VZcp2Rh/y5aeEsxCVABxwZE2xCx2uH0ytj+gs7mmGAkWaS4Qu7pb095FW6j8Ltx+w3h2BwOGo3fDFEFk0/k=
